# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-09 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problem',
            options={'ordering': ('index',)},
        ),
        migrations.AlterModelOptions(
            name='problemcategory',
            options={'ordering': ('index',)},
        ),
        migrations.AlterField(
            model_name='problem',
            name='index',
            field=models.IntegerField(db_index=True),
        ),
    ]
