# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-24 03:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_auto_20160521_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemcategory',
            name='is_audio_recording',
            field=models.BooleanField(default=False),
        ),
    ]
