# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-17 06:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0007_auto_20160615_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toilet',
            name='type',
            field=models.CharField(choices=[(b'C', b'Communal'), (b'P', b'Public'), (b'S', b'School'), (b'W', b'Women Sanitation Complex')], default=b'P', max_length=1),
        ),
    ]
