# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-17 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0008_auto_20160617_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='toilet',
            name='area',
            field=models.CharField(choices=[(b'R', b'Rural'), (b'U', b'Urban'), (b'PU', b'Peri Urban')], default=b'R', max_length=2),
        ),
        migrations.AlterField(
            model_name='toilet',
            name='payment',
            field=models.CharField(choices=[(b'P', b'Paid'), (b'F', b'Free'), (b'B', b'Both (Pay + No Pay)'), (b'H', b'Household Contribution')], default=b'F', max_length=1),
        ),
        migrations.AlterField(
            model_name='toilet',
            name='type',
            field=models.CharField(choices=[(b'C', b'Community'), (b'P', b'Public'), (b'S', b'School'), (b'W', b'Women Sanitation Complex')], default=b'P', max_length=1),
        ),
    ]
