# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-09 11:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manager', '0001_initial'),
        ('admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('pin_code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Manager')),
                ('problems', models.ManyToManyField(related_name='providers', to='admin.Problem')),
                ('toilets', models.ManyToManyField(related_name='providers', to='admin.Toilet')),
            ],
        ),
        migrations.AlterIndexTogether(
            name='provider',
            index_together=set([('provider_id', 'pin_code')]),
        ),
    ]
