# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-22 10:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0003_auto_20160522_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='providers', to='manager.Manager'),
        ),
    ]
