# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-17 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0005_provider_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='provider_code',
            field=models.CharField(choices=[(b'CLR', b'Cleaner'), (b'CTR', b'Caretaker'), (b'PLB', b'Plumber'), (b'SEW', b'Sewage Management'), (b'MGR', b'Water Management'), (b'VOL', b'Volunteer'), (b'CON', b'Contractor'), (b'MWM', b'Municipal Ward Member'), (b'NGO', b'Non-Govt. Organization')], default=b'CLR', max_length=5),
        ),
    ]
