# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-17 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0006_provider_provider_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='provider_code',
            field=models.CharField(choices=[(b'CLR', b'CLR: Cleaner'), (b'CTR', b'CTR: Caretaker'), (b'PLB', b'PLB: Plumber'), (b'SEW', b'SEW: Sewage Management'), (b'MGR', b'MGR: Water Management'), (b'VOL', b'VOL: Volunteer'), (b'CON', b'CON: Contractor'), (b'MWM', b'MWM: Municipal Ward Member'), (b'NGO', b'NGO: Non-Govt. Organization')], default=b'CLR', max_length=5),
        ),
    ]
