# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-28 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0007_auto_20160617_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='problems',
            field=models.ManyToManyField(related_name='providers', to='administration.ProblemCategory'),
        ),
    ]
