# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-09 11:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(db_index=True, max_length=15, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('status', models.IntegerField(default=0)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='admin.Problem')),
                ('toilet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='admin.Toilet')),
            ],
        ),
    ]
