# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-10 12:18
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_id',
            field=models.CharField(db_index=True, default=uuid.uuid4, max_length=15, unique=True),
        ),
    ]
