# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-10 16:40
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0002_auto_20160410_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_id',
            field=models.CharField(db_index=True, default=uuid.uuid4, max_length=40, unique=True),
        ),
    ]
