# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-21 04:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0002_auto_20160506_1806'),
        ('reporting', '0003_auto_20160410_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='provider.Provider'),
        ),
        migrations.AlterField(
            model_name='recording',
            name='provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='provider.Provider'),
        ),
    ]
