# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-26 10:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0004_auto_20160521_0933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recording',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='recording',
            name='ticket',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='provider.Provider'),
        ),
        migrations.DeleteModel(
            name='Recording',
        ),
    ]
