# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-26 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0005_auto_20160526_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_audio_present',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='is_provider_audio_present',
            field=models.BooleanField(default=False),
        ),
    ]
