# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-26 14:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0006_auto_20160526_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='provider.Provider'),
        ),
    ]
