# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-16 05:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0007_auto_20160526_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='provider_remarks',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AddField(
            model_name='ticket',
            name='user_remarks',
            field=models.TextField(blank=True, default=b''),
        ),
    ]
