# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-30 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0009_ticket_manager_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='additional_phone_numbers',
            field=models.CharField(default=None, max_length=65000),
        ),
        migrations.AddField(
            model_name='ticket',
            name='additional_timestamps',
            field=models.CharField(default=None, max_length=65000),
        ),
    ]
