# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-30 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0015_auto_20160731_0257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='additional_phone_numbers',
            field=models.CharField(blank=True, default=b'', max_length=65000, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='additional_timestamps',
            field=models.CharField(blank=True, default=b'', max_length=65000, null=True),
        ),
    ]
