# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-30 21:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0016_auto_20160731_0300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='additional_phone_numbers',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='additional_timestamps',
        ),
    ]
