# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-30 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0019_ticket_complaints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='complaints',
            field=models.IntegerField(default=1),
        ),
    ]
