# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-30 23:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0020_auto_20160731_0338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='additional_phone_numbers',
            new_name='additional_complaints_info',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='additional_timestamps',
        ),
    ]
