# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-20 04:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_auto_20160506_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='user_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='administration.UserProfile'),
        ),
    ]
