# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-22 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_auto_20160520_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='pin_code',
            field=models.CharField(default='0000', max_length=10),
            preserve_default=False,
        ),
    ]
