# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-23 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_manager_pin_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='manager_id',
            field=models.CharField(db_index=True, default=0, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterIndexTogether(
            name='manager',
            index_together=set([('manager_id', 'pin_code')]),
        ),
    ]
