# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-17 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_manager_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='manager_code',
            field=models.CharField(choices=[(b'MC', b'MC: Municipal Commissioner'), (b'MHO', b'MHO: Municipal Health Officer'), (b'MSI', b'MSI: Municipal Sanitary Inspecter'), (b'SS', b'SS: Sanitary Supervisor'), (b'DRDA', b'DRDA: District Rural Development Agent'), (b'BDO', b'BDO: Block District Officer'), (b'TSC', b'TSC: Total Sanitation Coordinator (Block)'), (b'SHM', b'SHM: School Head Master/Mistress')], default=b'MC', max_length=5),
        ),
    ]
